### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Dany-LF** [Androz2091/AutoAcceptNitro#1]
Tu devrais éviter ça, tu vas surtout provoquer une vague de ban

**Comment by Androz2091** [comment]
Bonsoir,
Comme précisé dans le README, AutoAcceptNitro utilise BetterDiscord, qui est très clairement indiqué comme un logiciel allant à l'encontre des C.G.U Discord sur la plupart des sites. Je prends donc comme acquis le fait que les utilisateurs soient au courant des risques qu'ils courent en utilisant BetterDiscord.

**Comment by Androz2091** [comment]
@Dany-LF j'ai ajouté une section Disclaimer au README.

**Comment by Dany-LF** [comment]
> 
> 
> @Dany-LF j'ai ajouté une section Disclaimer au README.

parfait merci bien!
